#
# 该文件包含用于自定义站点的配置标志
#

# 您的站点名称（显示在标题中）
name: "lbirey 博客"
# 简短的简介或描述（显示在标题中）
description: "个人技术资源 | 日常分享"

# 背景图片 URL
background_image: "https://api.suyanw.cn/api/scenery.php" # 替换为您背景图的实际 URL

# 下面的标志是可选的
# 你的头像或个人资料图片的 URL（你可以使用你的 GitHub 个人资料图片）
avatar: https://api.suyanw.cn/api/mcapi.php
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://d29fhpw069ctt2.cloudfront.net/icon/image/120252/preview.svg

# 标题中的选项卡。有“博客”、“关于”、“存档”、“标签”
# 和 URL 链接（例如下面的“主题”选项卡）选项卡。如果不需要的话删除即可
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /关于
  - name: 归档
    url: /存档
  - name: 标签
    url: /标签

# 分页
paginate: 8

# 在页脚中为您输入的每个用户名添加一个图标
footer_links:
  weibo: https://www.weibo.com/<thispart> # 请替换为您的微博链接
  behavior: https://wob.us.kg/<用户名>
  zhihu: https://www.zhihu.com/people/lbirey
  email: lbirey@outlook.com
  github: https://github.com/lbirey
  rss: # 只需在此输入任何内容即可获得可用的 RSS 图标

# 页脚图标下的文本
footer_text: 版权 (c) 2019 柠檬

# 输入您的 Disqus 简称（不是您的用户名）以启用对帖子的评论
disqus: your_disqus_shortname

# Gitalk 配置
gitalk:
  clientID: bd65d5c0df878155b7fa
  clientSecret: d0220762c05c2d6b6f6152a0f0e4b6b090de9729
  repo: lbirey.github.io
  owner: lbirey

# 您的网站 URL
url: https://lbirey.github.io

# !! 您不需要更改下面的配置标志 !!
permalink: /:title/
paginate_path: /page:num/

# Jekyll 版本
version: v1.2.0

# Markdown 和 Sass 配置
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 

# 插件
plugins:
  - jekyll-sitemap # 创建 Sitemap
  - jekyll-feed # 创建 Atom feed
  - jekyll-paginate

# 排除的文件
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
